# ── Light Mode──

background = #fffcf0
foreground = #1a1917
cursor-color = #cc785c
cursor-text = #fffcf0
selection-background = #f5e1d0
selection-foreground = #1a1917

palette = 0=#1a1917
palette = 1=#a84b3a
palette = 2=#2e7c4c
palette = 3=#8a6220
palette = 4=#207fde
palette = 5=#6a5bcc
palette = 6=#2e5f99
palette = 7=#746e64
palette = 8=#8d877d
palette = 9=#c45f4a
palette = 10=#5e8f6d
palette = 11=#9c7a39
palette = 12=#4f79a8
palette = 13=#6d5dbd
palette = 14=#45809e
palette = 15=#4a473f
